[default]
host = "golandia.c6u7gxmxwmst.us-east-1.rds.amazonaws.com"
port = "3306"
database = "user"
user = "golandia"
password ="golandia123"
charset = "utf8"
sql_log = true

MaxIdleConns = 10 
MaxOpenConns = 100 
